---
database_url: "{{ lookup('env', 'DATABASE_URL') }}"
debug: "{{ lookup('env', 'DEBUG') }}"
domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
localdev: "{{ lookup('env', 'LOCALDEV') }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
secret_key: "{{ lookup('env', 'SECRET_KEY') }}"
stripe_publishable_key: "{{ lookup('env', 'STRIPE_PUBLISHABLE_KEY') }}"
stripe_secret_key: "{{ lookup('env', 'STRIPE_SECRET_KEY') }}"
stripe_webhook_secret: "{{ lookup('env', 'STRIPE_WEBHOOK_SECRET') }}"
stripe_price_id: "{{ lookup('env', 'STRIPE_PRICE_ID') }}"
